package com.example.submissioncompose.model


import com.example.submissioncompose.R


object BookDataStore {
    val listOfBooks = listOf(
        Book(1, R.drawable.bumi, "Novel Bumi", "120.0000", "Namaku Raib, usiaku 15 tahun, kelas sepuluh. Aku anak perempuan seperti kalian, adik-adik kalian, tetangga kalian. Aku punya dua kucing, namanya si Putih dan si Hitam. Mama dan papaku menyenangkan. Guru-guru di sekolahku seru. Teman-temanku baik dan kompak. Aku sama seperti remaja kebanyakan, kecuali satu hal. Sesuatu yang kusimpan sendiri sejak kecil. Sesuatu yang menakjubkan. Namaku, Raib. Dan aku bisa menghilang", "Ini adalah Novel serial pertama dari series Bumi Karya Tere Liye"),
        Book(2, R.drawable.bulan, "Novel Bulan", "100.000", "Namanya Seli, usianya 15 tahun, kelas sepuluh. Dia sama seperti remaja yang lain. Menyukai hal yang sama, mendengarkan lagu-lagu yang sama, pergi ke gerai fast food, menonton serial drama, film, dan hal-hal yang disukai remaja. Tetapi ada sebuah rahasia kecil Seli yang tidak pernah diketahui siapa pun. Sesuatu yang dia simpan sendiri sejak kecil. Sesuatu yang menakjubkan dengan tangannya. Namanya Seli. Dan tangannya bisa mengeluarkan petir", "Ini adalah Novel serial kedua dari series Bumi Karya Tere Liye"),
        Book(3, R.drawable.matahari, "Novel Matahari", "99.000", "Namanya Ali, 15 tahun, kelas 10. Jika saja orangtuanya mengizinkan, seharusnya dia sudah duduk di tingkat akhir ilmu fisika program doktor di universitas ternama.\nAli tidak menyukai sekolahnya, guru-gurunya, teman-teman sekelasnya. Semua membosankan baginya. Tapi sejak dia mengetahui ada yang aneh pada diriku dan Seli, teman sekelasnya, hidupnya yang membosankan berubah seru. Aku bisa menghilang, dan Seli bisa mengeluarkan petir. Ali sendiri punya rahasia kecil. Dia bisa berubah menjadi beruang raksasa. Kami bertiga kemudian bertualang ke tempat-tempat menakjubkan.","Ini adalah Novel serial ketiga dari series Bumi Karya Tere Liye"),
        Book(4, R.drawable.bintang, "Novel Bintang", "109.000", "Namaku Raib, aku bisa menghilang. Seli, teman semejaku, bisa mengeluarkan petir dari telapak tangannya. Dan Ali, si biang kerok sekaligus si genius, bisa berubah menjadi beruang raksasa. Kami bertiga kemudian bertualang ke dunia paralel yang tidak diketahui banyak orang, yang disebut Klan Bumi, Klan Bulan, Klan Matahari, dan Klan Bintang. Kami bertemu tokoh-tokoh hebat. Penduduk klan lain. Ini petualangan keempat kami. Setelah tiga kali berhasil menyelamatkan dunia paralel dari kehancuran besar, kami harus menyaksikan bahwa kamilah yang melepaskan musuh besar-nya. Ini ternyata bukan akhir petualangan, ini justru awal dari semuanya","Ini adalah Novel serial keempat dari series Bumi Karya Tere Liye"),
        Book(5, R.drawable.cerosdanbatozar, "Novel Ceros dan Batozar", "110.000", "Awalnya kami hanya mengikuti karyawisata biasa seperti murid-murid sekolah lain. Hingga Ali, dengan kegeniusan dan keisengannya, memutuskan menyelidiki sebuah ruangan kuno. Kami tiba di bagian dunia paralel lainnya, menemui petarung kuat, mendapat kekuatan baru serta teknik-teknik menakjubkan. Dunia paralel ternyata sangat luas, dengan begitu banyak orang hebat di dalamnya.","Ini adalah Novel serial kelima dari series Bumi Karya Tere Liye"),
        Book(6, R.drawable.komet, "Novel Komet", "110.000", "Setelah “musuh besar” kami lolos, dunia parallel dalam situasi genting. Hanya soal waktu, pertempuran besar akan terjadi. Bagaimana jika ribuan petarung yang bisa menghilang, mengeluarkan petir, termasuk teknologi maju lainnya muncul di permukaan Bumi?. Tidak ada yang bisa membayangkan kekacauan yang akan terjadi. Situasi menjadi lebih rumit lagi saat Ali, pada detik terakhir, melompat ke portal menuju Klan Komet. Kami bertiga tersesat di klan asing untuk mencari pusaka paling hebat di dunia paralel","Ini adalah Novel serial keenam dari series Bumi Karya Tere Liye"),
        Book(7, R.drawable.kometminor, "Novel Komet Minor", "108.000", "Pertarungan melawan si Tanpa Mahkota akan berakhir di sini. Siapa pun yang menang, semua berakhir di sini, di Klan Komet Minor, tempat aliansi para pemburu pernah dibentuk, dan pusaka hebat pernah diciptakan. Dalam saga terakhir melawan si Tanpa Mahkota, aku, Seli, dan Ali menemukan teman seperjalanan yang hebat. Bersama-sama kami melewati berbagai rintangan, memahami banyak hal, berlatih teknik baru, dan bertarung bersama-sama.","Ini adalah Novel serial ketujuh dari series Bumi Karya Tere Liye"),
        Book(8, R.drawable.selena, "Novel Selena", "89.000", "SELENA dan NEBULA adalah buku ke-8 dan ke-9 yang menceritakan siapa orangtua Raib dalam serial petualangan dunia paralel. Dua buku ini sebaiknya dibaca berurutan. Kedua buku ini juga bercerita tentang Akademi Bayangan Tingkat Tinggi, sekolah terbaik di seluruh Klan Bulan. Tentang persahabatan tiga mahasiswa, yang diam-diam memiliki rencana bertualang ke tempat-tempat jauh. Tapi petualangan itu berakhir buruk, saat persahabatan mereka diuji dengan rasa suka, egoisme, dan pengkhianatan.","Ini adalah Novel serial kedelapan dari series Bumi Karya Tere Liye"),
        Book(9, R.drawable.nebula, "Novel Nebula", "110.000", "SELENA dan NEBULA adalah buku ke-8 dan ke-9 yang menceritakan siapa orangtua Raib dalam serial petualangan dunia paralel. Dua buku ini sebaiknya dibaca berurutan. Kedua buku ini juga bercerita tentang Akademi Bayangan Tingkat Tinggi, sekolah terbaik di seluruh Klan Bulan. Tentang persahabatan tiga mahasiswa, yang diam-diam memiliki rencana bertualang ke tempat-tempat jauh. Tapi petualangan itu berakhir buruk, saat persahabatan mereka diuji dengan rasa suka, egoisme, dan pengkhianatan.","Ini adalah Novel serial kesembilan dari series Bumi Karya Tere Liye"),
        Book(10, R.drawable.siputih, "Novel Si Putih", "99.000", "Bagaimana jika hewan kesayangan kalian ternyata hewan dengan kekuatan terbesar di dunia paralel? Bagaimana jika hewan yang terlihat imut, menggemaskan, ternyata bisa menjadi salah satu petarung paling hebat?. Kisah ini tentang si Putih, kucing kesayangan Raib. Masa lalu si Putih tidak kalah menarik, sebelum akhirnya kucing itu diletakkan di depan pintu rumah sebagai hadiah ulang tahun Raib.","Ini adalah Novel serial kesepuluh dari series Bumi Karya Tere Liye"),
        Book(11, R.drawable.bibigill_1, "Novel Bibi Gill", "120.000", "Bagaimana menjadi petarung terkuat di dunia paralel? Dengan latihan panjang dan pengorbanan. Termasuk kehilangan dan kesedihan. Inilah kisah tentang Bibi Gill, yang sejak kecil berusaha mengalahkan monster dalam hidupnya.Apakah dia bisa menemukan jawaban yang selama ini dia cari?\nHei, jika kalian melihat seseorang yang amat sederhana, seperti ibu-ibu penjaga kantin, tukang sapu, sopir ojek online. Jangan buru-buru menilainya memang sesederhana itu. Boleh jadi dia adalah pemilik teknik bertarung paling mematikan di dunia paralel.","Ini adalah Novel serial kesebelas dari series Bumi Karya Tere Liye"),
        Book(12, R.drawable.lumpu, "Novel Lumpu", "100.000", "Yes! Akhirnya, Raib, Seli, dan Ali kembali bertualang. Kalian sudah kangen dengan trio ini? Misi mereka adalah menyelamatkan Miss Selena, guru matematika mereka. Tapi, apakah semua berjalan mudah? Siapa yang bersedia membantu mereka? Kali ini, si genius Ali memutuskan meminta bantuan dari sosok yang tidak terduga, karena musuh dari musuh adalah teman.\\n Apakah Raib bisa melupakan masa lalu itu dengan memaafkan Miss Selena? Bagaimana dengan Tazk? Apakah Raib bisa bertemu lagi dengan ayahnya, atau itu masih menjadi misteri? Bagaimana dengan jejak ekspedisi Klan Aldebaran 40.000 tahun lalu? ","Ini adalah Novel serial ketigabelas dari series Bumi Karya Tere Liye"),
        Book(13, R.drawable.sagaras, "Novel SagaraS", "120.000", "Ali, bertahun-tahun, berusaha memecahkan misteri itu. Raib dan Seli tentu tidak akan membiarkan Ali sendirian, mereka sahabat sejati. Dan jangan lupakan, Batozar alias Master B, dengan segenap kalimat kasar, seolah tidak peduli, dia selalu siap membela. Tapi bagaimana jika misteri itu terhadang tembok kokoh SagaraS? Dan mereka harus bertarung hidup-mati lima ronde melawan Ksatria SagaraS?","ini adalah Novel serial keduabelas dari serial Bumi Karya Tere Liye")
        )
}